# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rcpp_add
#' @description The sum of two integers.This is a simple function to test the integrity of Rcpp package
#' @param the first parameter x (int)
#' @param the second parameter y (y)
#' @return the sum of two integers \code{n}
#' @examples
#' \dontrun{
#' x<-3
#' y<-4
#' z<-rcpp_add(3,4)
#' }
#' @export
rcpp_add <- function(x, y) {
    .Call(`_SC19017016_rcpp_add`, x, y)
}

